#!/usr/bin/env python3

# Copyright © 2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import sys
import lxml.etree as etree

ns = dict(svg='http://www.w3.org/2000/svg')

def ntag(prefix, tag):
    return '{' + ns[prefix] + '}' + tag

def main():
    ap = argparse.ArgumentParser(usage='%(prog)s < SVGFILE')
    ap.parse_args()
    if sys.stdin.isatty():
        ap.error('stdin is a tty')
    doc = etree.parse(sys.stdin.buffer)
    px = py = -1e999
    width = 1e999
    for elt in doc.iterfind('//svg:text', namespaces=ns):
        x = int(elt.get('x'))
        y = int(elt.get('y'))
        if y == py:
            dx = x - px
            if dx < width:
                width = dx
        py = y
        px = x
    px = py = -1e999
    pelt = None
    for elt in doc.iterfind('//*', namespaces=ns):
        if elt.tag != ntag('svg', 'text'):
            elt.text = ''
        elt.tail = ''
    for elt in doc.iterfind('//svg:text', namespaces=ns):
        x = int(elt.get('x'))
        y = int(elt.get('y'))
        if y == py:
            dx = x - px
            if dx != width:
                pelt.tail = ' '
        py = y
        px = x
        pelt = elt
    for elt in doc.iter():
        if elt.tag == etree.Comment:
            elt.tail = '\n'
            elt.text = None
    elt = doc.getroot()
    elt.text = '\n'
    elt = elt.find('./svg:g', namespaces=ns)
    elt.text = '\n'
    elt.tail = '\n'
    elt[-1].tail = '\n'
    doc.write(sys.stdout.buffer, encoding='UTF-8')
    sys.stdout.buffer.write(b'\n')

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
